### ISSUE TITLE
It won't work if you're using a reverse proxy(or load blancer)

### ISSUE THREAD

**Issue by mizunago** [hokkaidoperson/DokuWiki-AccsCounter-Plugin#16]
Running a dokuwiki in a docker container, accessed through a reverse proxy (nginx)
In this case, it is always the IP address of the container host (such as 172.23.0.1 or a local address), and it does not count correctly.

For this to work under a proxy or load balancer, you have to look at X-Forwarded-For, not REMOTE_ADDR.
X-Forwarded-For is not a required header and is a forgeable header, so it will not be as accurate, but it can work in an environment such as AWS ELB.
In order to know if the reverse proxy has forwarded the message, there is an X-Forwarded-For header

dokuwiki を docker コンテナで動作させ、リバースプロキシ(nginx) を使ってアクセスさせています
この場合、常にコンテナホストのIPアドレス（172.23.0.1 のようなローカルアドレス）となってしまい、正常にカウントしません。

これをプロキシやロードバランサーの配下で動作させるには、REMOTE_ADDR ではなく、X-Forwarded-For を見なければなりません。
X-Forwarded-For は必須ヘッダではなく、改竄可能なヘッダのため、正確性は下がりますが、AWS の ELB といった環境下でも動作させることができます。
リバースプロキシが転送したかどうかを知るには、X-Forwarded-For ヘッダがあります

https://ja.wikipedia.org/wiki/X-Forwarded-For

**Comment by mizunago** [comment]
I am resolved by follow code.
However, it is not generic and should not be implemented as is. 

私は以下のような方法で解決できましたが、
これは汎用性がありません。（必ず意図したヘッダー(X-Real-IP)があること、且つ自分で用意した安全なプロキシサーバを使っているという前提がある場合のみです）

nginx settings: 
```
        proxy_set_header    Host    $host;
        proxy_set_header    X-Real-IP    $remote_addr; # ! IMPORTANT HERE !
        proxy_set_header    X-Forwarded-Host       $host;
        proxy_set_header    X-Forwarded-Server    $host;
        proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
```

Replace it: `syntax/counter.php`
以下のように置換します

```
s/REMOTE_ADDR/HTTP_X_REAL_IP/g
```

**Comment by hokkaidoperson** [comment]
I found that DokuWiki already has a function that copes with X-Forwarded-For and X-Real-IP, so I used it.

X-Forwarded-ForやX-Real-IPについて対処する関数がDokuWikiに既にある事が分かったので、それを使いました。
