### ISSUE TITLE
Counter data is shared among multiple sites when using farmer plugin

### ISSUE THREAD

**Issue by shimmtak** [hokkaidoperson/DokuWiki-AccsCounter-Plugin#2]
Hi, thank you for your nice tool. 
When using your tool with the "farmer" plugin, the counter data is share by multiple sites unexpectedly.
It sums up the access count data from all sites.
"Farmer" is one of useful plugins of Dokuwiki, which can create multiple "children" (called animals) site.
I hope your plugin to be compatible with it. 
It seems that the counter data is stored in `lib/plugins/accscounter/log`, which is shared by all animals and farmer sites.
I hope the log to be placed under `data` directory such as `data/meta`.  It is separately held by each animal site. Some other statistics plugins use the directory (for example, "logstats", "quickstats").

**Comment by hokkaidoperson** [comment]
Thanks for your report.  I didn't care about the farmer plugin.
I'll attempt to fix the problem (I'll make my plugin store datas in data/meta directory), so please wait until I finish the work.

**Comment by hokkaidoperson** [comment]
I found out about the function metaFN.  I'll try it.

**Comment by hokkaidoperson** [comment]
Memorandum for myself

- Function idx_get_indexer()->getPages() gets all page names of the wiki
- metaFN($id, '.accscounternm') for general counter data, metaFN($id, '.accscounterip') for IPs log data

**Comment by shimmtak** [comment]
Thank you for your effort.
I tried very quick modification like below:

        //define('COUNTER_DIR', DOKU_PLUGIN . 'accscounter/log/');
        $pagemetaFN = metaFN($INFO['id'], '.meta');
        $pagepath = str_replace(':','/',$pagemetaFN);
        $counterdir = str_replace($INFO['id'] . '.meta', '', $pagepath);
        $counterdir = $counterdir . "accscounter/log/";
        define('COUNTER_DIR', $counterdir);

Yes, it might not be good use of the metaFN(), but anyway, it worked. Hope this helps.

**Comment by hokkaidoperson** [comment]
Thanks for your suggestion, but I've finished fixing the issue today.
I'm sorry that I couldn't utilize your comment (_ _;)
I tested my new script for several times, and it seems to work well, so I'll publish it from now.

**Comment by hokkaidoperson** [comment]
I've published the new version of this plugin.
Does it work well on your wiki?

**Comment by shimmtak** [comment]
Thank you for the great modification. The data transferring is nice.
However, please care about uninstalling. So it is better that the counter files are placed under subdirectory like `data/meta/accscounter/`.  I am sorry I could not explain about that before. (_ _;)
I like your tool, but not all of dokuwiki users will use a plugin in long term, so, good plugins are also easy to uninstall. 
Files like `"* .accscounternm"` (and perhaps `* .accscounterip` ?) are difficult to erase because they are widely distributed under the `data/meta`. I think that placing them into `data/meta/accscounter/` subdirectory is good and enough. Users can easily delete it by hand (or keep and reuse it when they reinstall the plugin later).
I am glad if you consider about it, and again, I am sorry I could not explain about it in advance.

**Comment by hokkaidoperson** [comment]
Thank you for your opinion.  I didn't care about uninstalling very much.
I'm going to make a tool with which you can easily control the log files.  Please wait until I complete the tool.
