### ISSUE TITLE
Easy way to control the log files

### ISSUE THREAD

**Issue by hokkaidoperson** [hokkaidoperson/DokuWiki-AccsCounter-Plugin#3]
[English]
A request from @shimmtak , suggesting to make this plugin easy to uninstall.
I didn't care about uninstalling this plugin, so log files of the number of accesses `*.accscounternm` are widely distributed under directory `data/meta`.
I'm going to change the saving destination to `data/meta/_accscounter`, but current `*.accscounternm` files won't become useless, I'll make a function to transfer the log.

Also, I'm planning to make a tool so that we can easily control the log files.  This tool will make it easier to show or delete the log data.

Please wait until I finish my work.

_Originally posted by @shimmtak in https://github.com/hokkaidoperson/DokuWiki-AccsCounter-Plugin/issues/2#issuecomment-462100616_

P.S.: I updated the plugin. https://github.com/hokkaidoperson/DokuWiki-AccsCounter-Plugin/commit/da05aa315d207b9853d5cb86bd2e21400d46f515

[Japanese/日本語]
@shimmtak さんからのリクエストで、プラグインのアンインストールを容易にするための変更です。
開発当時、プラグインをアンインストールする際の事について考えてなかったため、アクセス数のログファイル`*.accscounternm`が`data/meta`中あちこちに生成されるようになっています。
次回のアップデートで、データの保存先を`data/meta/_accscounter`に変更予定ですが、現在の`*.accscounternm`も無駄にはせず、新しい保存先にログを転送する機能を手配します。
また、ログファイルを簡単にコントロール出来るようにするツールを開発予定です。ツールを使う事で、ファイルの閲覧や削除が容易に行えるようになります。

完成までしばらくお待ち下さい。

追記：プラグインをアップデートしました。https://github.com/hokkaidoperson/DokuWiki-AccsCounter-Plugin/commit/da05aa315d207b9853d5cb86bd2e21400d46f515

_元の投稿（英語）：https://github.com/hokkaidoperson/DokuWiki-AccsCounter-Plugin/issues/2#issuecomment-462100616_

**Comment by shimmtak** [comment]
ご検討ありがとうございます。コントロールするツールが加われば大変便利かと思います。

データの置き場所ですが、やはり `data/meta/accescounter` など、サブディレクトリの下がよろしいのではないかと思います。理由ですが、`data/meta` に元からある `.meta` などのファイルは、コア機能で使うものでもあり、プラグイン固有のファイルとは混ざらない方が好ましいと思われるためです。
（もともと `data/meta/` の下をお勧めしたのは私ですが、この点の説明が足りず申し訳ありません)

[quickstats](https://github.com/turnermm/quickstats)も、`data/meta/quickstats` をデータの置き場所としており、参考になるかもしれません。

ところで、アクセス統計関係のプラグインはいくつかありますが、その中でも AccsCounter は今日/昨日のアクセス数が表示できる所などが気に入っています。ちなみに、dokuwikiコミュニティとの共有を考え、なるべく英語を使うようにしておりましたが、私も日本人です。よろしくお願いします。

**Comment by hokkaidoperson** [comment]
ご意見ありがとうございます。とりあえず`data/meta/_accscounter`というディレクトリを作成し、その下にログを保存する方向で調整する予定です（現在のプラグインで生成される`.accscounternm`ファイルを`_accscounter`ディレクトリ内に移動する機能も整備します）。アンダースコアを入れたのは、「accscounter」という名前空間に属するページ（accscounter:01 など）のメタファイルとごっちゃにならないようにして（あまり無いケースだとは思いますが）、全消去などの処理を簡単にするためです。

余談ですが、僕がGithubで日本語OKの開発者さんと会話する時は日本語で普通に話し掛けてます（トピックのタイトルは日本語と英語の両方で記載しています）。
とりあえず、このトピックの一番上に、更新予定の内容を英語と日本語両方で書いておきます。

**Comment by shimmtak** [comment]
はい、`data/meta/_accscounter` とアンダースコアの入ったディレクトリ名にするのはとても良い考えだと思います。
そういえば、dokuwikiでは、ページ作成のときのテンプレートなどの特殊なファイル名にはアンダースコアをつけておりますので、スタイルとしても整っており非常に良いと思います。

**Comment by hokkaidoperson** [comment]
ありがとうございます。

プラグインに関して本格的に作業するのは私の大学入試（二次試験前期）が終わってからになりそうなので、また少しお時間を頂戴してしまう事になりますが、どうぞよろしくお願い致します。

**Comment by shimmtak** [comment]
もちろん hokkaidoperson さんのツールですから、私のことは気にせず、ご自分のスケジュール、ペースでプログラミングなさってくださればと思います。
それにしても hokkaidoperson さんは大学受験生でしたか！英語もプログラミングも素晴らしいので、大学受験もきっと良い結果になると思います。受験最優先で、健康にお気をつけて頑張ってください。

**Comment by hokkaidoperson** [comment]
ありがとうございます。あまり自信は無いですが頑張って来ようと思います。

**Comment by hokkaidoperson** [comment]
受験が終わった（合格発表は今週木曜日ですが自信無いです）ので、こちらの案件にも本格的に取り組もうかと思います。
完成までしばらくお待ち下さい。

**Comment by shimmtak** [comment]
受験お疲れ様でした。イシューの扱いは、マイペースで結構だと思います。貴重な春休み、有意義にお過ごしください。

**Comment by hokkaidoperson** [comment]
ありがとうございます。アップデートの進捗に関しては、本日、データ移動の機能を一通り完成させて、データ管理機能の作成に取り掛かったところです。
プログラミング以外の時間帯は、YouTubeを見たり外出したりとのんびり過ごしております。

**Comment by hokkaidoperson** [comment]
アクセスカウンタープラグインのアップデートを行いました。ご要望のあった「保存先の変更」を行った他、予告通りログデータ管理機能（データマネージャー）を追加しました。
私が保有するWikiで動作確認は行い、さしあたり問題は無さそうでしたが、もし不具合がありましたらご連絡お願いします。

**Comment by shimmtak** [comment]
おくればせながらアップデートし、ログの移動機能を使用したところ、問題無く動きました。farmer プラグインを使用した場合も予期したとおり別々のカウンターとして機能しています。もし何か不具合あればお伝えしたいと思います。どうもありがとうございました。
