### ISSUE TITLE
Asking for a new option in configuration

### ISSUE THREAD

**Issue by prschopf** [hokkaidoperson/DokuWiki-AccsCounter-Plugin#4]
Im using this pluggin and its great! But I have a lot of robots from China, USA, France, etc. So, I put these countries in "Countries that will be exluded" option.

My problem is: Every week I check who is accessing my wiki and there are more robots from others countries. So, I have to update this option again and again.

This is getting boring and I need to check that every week. Is there a way to create a reverse option, like "Countries that will be included"? In this way I would add just a few countries instead a huge list.

**Comment by hokkaidoperson** [comment]
Hello, thank you for using my plugin.
I'll consider adding the option "countries that will be included".

You can also consider using the data manager, a part of the access counter plugin.
The data manager has the spammer check function.  The spammer check function needs Stopforumspam2 plugin (See https://www.dokuwiki.org/plugin:stopforumspam2).
After installing Stopforumspam2 plugin, go to "Admin" -> "Additional Plugins" -> "Access Counter - Data Manager", and select the data to use for the spammer check, then scroll down, choose "Spammer Check", and push "Run".  I think you can remove accesses by spammers easier by using this plugin.

**Comment by prschopf** [comment]
Hi,

Thanks for your quick reply.

Will stopforumspam2 stop robots also? I dont want to stop robots to visit my wiki. I just want they dont sum in AccsCounter.

**Comment by hokkaidoperson** [comment]
The stopforumspam2 plugin doesn't prevent robots from accessing unless you enable the setting "accessRefusalFreq" or "accessRefusalConf" (they are disabled in default).
In default the plugin protects the edit form and the user registration form from robots.  If you wanna disable that, change the setting "protectRegFreq", "protectRegConf", "protectEditFreq", and (or) "protectEditConf" to "0".

Also, don't forget to change the access counter's setting "sfsExFreq" and (or) "sfsExConf", or the stopforumspam2 plugin can't take away accesses from robots.

**Comment by prschopf** [comment]
My problem is not with forms. In fact, its a closed wiki and I dont have problems with robots. Its for Brazilian people, so, I dont care about access from other countries (robots or not).

I would like to count access only for Brazilian people (or Brazilian robots).

**Comment by hokkaidoperson** [comment]
I see.  I'll consider adding the option like "countries that will be included".

**Comment by prschopf** [comment]
Thank you!

**Comment by hokkaidoperson** [comment]
I'm sorry that I got late to give you a new function that solves this issue.
I added the function you wanted, "Set specific countries to be counted"

**Comment by prschopf** [comment]
Installed and working fine!

**Comment by hokkaidoperson** [comment]
That's fine!

**Comment by prschopf** [comment]
Is it really working? After this change I got no more visits in my forum...

**Comment by hokkaidoperson** [comment]
I'm sorry, this is because of a bug of the new option...

I fixed it just now, please update my plugin.

**Comment by prschopf** [comment]
I think its solved now, thanks again!
